### ISSUE TITLE
Is there a pytorch2caffe.py tool?

### ISSUE THREAD

**Issue by wk910930** [marvis/pytorch-caffe-darknet-convert#1]
Dear @marvis ,

Thank you for the great work! I was wondering if there is a tool that can convert from PyTorch (i.e. *.pth) to Caffe (i.e. *.caffemodel) directly? This is gonna be useful. Is there any concern if this tool does not exist?

Thanks!
Kun

**Comment by marvis** [comment]
It's possible  if the network structure can be extracted from .pth automatically.

**Comment by marvis** [comment]
@wk910930  I implement the pytorch2caffe.py tool, which can convert pytorch model to prototxt and caffemodel. I check the prototxt is correct. The converted caffemodel still needs to verify.
