### ISSUE TITLE
Error in running the default script for pytorch2caffe

### ISSUE THREAD

**Issue by stalagmite7** [marvis/pytorch-caffe-darknet-convert#10]
I am trying to run the pytorch2caffe script as it is (no changes, so it downloads the resnet50 model), but I get this error:

    .
    .
    converting ThresholdBackward188
		converting AvgPool2dBackward189
		converting ViewBackward190
		converting AddmmBackward190
		Traceback (most recent call last):
		  File "pytorch2caffe.py", line 234, in <module>
		    pytorch2caffe(input_var, output_var, 'resnet50-pytorch2caffe.prototxt', 'resnet50-pytorch2caffe.caffemodel')
		  File "pytorch2caffe.py", line 76, in pytorch2caffe
		    convert_layer(output_var.grad_fn)
		  File "pytorch2caffe.py", line 74, in convert_layer
		    save_fc2caffe(weights, biases, params[parent_name])
		  File "pytorch2caffe.py", line 87, in save_fc2caffe
		    fc_param[0].data[...] = weights.numpy() 
		ValueError: could not broadcast input array from shape (1000,2048) into shape (1000,8192)

What seems to be the issue here, @marvis ? Appreciate any light you could shed on this!

**Comment by marvis** [comment]
to make pytorch2caffe.py work, you need to change the ceil function in caffe's pooling layer to floor
