### ISSUE TITLE
Squeeze layer implemented?

### ISSUE THREAD

**Issue by stalagmite7** [marvis/pytorch-caffe-darknet-convert#11]
I am trying to convert a pytorch model into a caffe model. My pytorch model has a squeeze layer becasue it uses RNNs at the last two layers, and the pytorch2caffe conversion gives me this error:
    
    File "pytorch2caffe.py", line 140, in add_layer
    layer['type'] = layer_dict[parent_type]
    KeyError: 'SqueezeBackward'

Is this because the squeeze layer is not implemented in your code? And is there a possible quick-fix to this issue?

**Comment by marvis** [comment]
squeeze layer is not implemented. You can add corresponding parsing of squeeze layer in pytorch2prototxt and pytorch2caffe，and then add save_squeeze2caffe to save weights.
