### ISSUE TITLE
convert pytorch model directly to caffe model

### ISSUE THREAD

**Issue by raymon-tian** [marvis/pytorch-caffe-darknet-convert#2]
Hi,
 is there some way to convert pytorch model directly to caffe model?  Thanks :)

**Comment by marvis** [comment]
Hi raymon-tian:

you can check pytorch2caffe.py which could convert resnet50 from torchvision models directly into caffe model.

**Comment by BowieHsu** [comment]
Hi, marvis, thank your for your great work, i'm trying to convert pytorch pth file to caffemodel with your demo, but i get error like this 
![default](https://user-images.githubusercontent.com/4092342/29058789-ce7ab296-7c44-11e7-8c39-d9b51b3eebf5.JPG)

i am trying to figure it out but i have no idea where should i begin, so i want to check which version of pytorch and caffe on your OS, or did i miss any installment tips which you didn't mention in the ReadMe?

Many thanks.

**Comment by marvis** [comment]
@BowieHsu  seems your model is loaded in GPU mode, in my demo the model and variable are all in cpu mode. BTW, pytorch needs to install from source.
