### ISSUE TITLE
KeyError: 'BroadcastBackward'

### ISSUE THREAD

**Issue by rainfalj** [marvis/pytorch-caffe-darknet-convert#25]
KeyError: 'BroadcastBackward'

**Comment by oya163** [comment]
Can you try pytorch=0.2 and torchvision=0.1.8 ?

**Comment by rainfalj** [comment]
Thank you, I have solved it

**Comment by ShadowLau** [comment]
@rainfalj sorry to reopen this question. Recently, I have met the same problem, could you tell me how to fix  that?
