### ISSUE TITLE
detect.py caffe implementation

### ISSUE THREAD

**Issue by fishman2008** [marvis/pytorch-caffe-darknet-convert#3]
hi marvis, once the darknet model is converted to caffe and the detect.py is used to test the converted model, it still uses torch to compute the forward rather than the caffe? Another question is that the converted model has lower mAp than the original voc.model which is 57.1. What is the reasons for the performance drop? Thanks.

**Comment by marvis** [comment]
1. Yes, the class CaffeNet in caffenet.py can load prototxt/caffemodel directly.
2. I test tiny-yolo-voc.weights with input size 416x416, the mAP is  0.5410.  I don't know the reason.
