### ISSUE TITLE
Issue converting AddmmBackward

### ISSUE THREAD

**Issue by RomanovMikeV** [marvis/pytorch-caffe-darknet-convert#4]
Hi! I am running your code with `python pytorch2caffe.py` and I have the following issue:

```
converting AvgPool2dBackward189                                                                             
converting ViewBackward190                                                                                  
converting AddmmBackward190                                                                                 
Traceback (most recent call last):                                                                          
  File "pytorch2caffe.py", line 234, in <module>                                                            
    pytorch2caffe(input_var, output_var, 'resnet50-pytorch2caffe.prototxt', 'resnet50-pytorch2caffe.caffemod
el')                                                                                                        
  File "pytorch2caffe.py", line 76, in pytorch2caffe                                                        
    convert_layer(output_var.grad_fn)                                                                       
  File "pytorch2caffe.py", line 74, in convert_layer                                                        
    save_fc2caffe(weights, biases, params[parent_name])                                                     
  File "pytorch2caffe.py", line 87, in save_fc2caffe                                                        
    fc_param[0].data[...] = weights.numpy()                                                                 
ValueError: could not broadcast input array from shape (1000,2048) into shape (1000,8192)  
```

**Comment by marvis** [comment]
Very good question. This due to the different pooling operation between pytorch and caffe. Just replace the ceil function to floor in pooling layer will fix the problem.
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L90-L92

**Comment by RomanovMikeV** [comment]
I have tried increasing kernel size to 8 manually in pytorch model before conversion. This didn't change anything, though, if you look at those lines, the new output size shout then change from 2 to 1...

**Comment by marvis** [comment]
why increase kernel size？I am confused about your problem.

**Comment by BowieHsu** [comment]
@marvis  Hi, I meet the same problem but i modified the input image size from 1 3 224 224 to 1 3 200 200, then it produced caffemodel and prototxt file successfully, does my solution may create bugs?

**Comment by marvis** [comment]
@BowieHsu This is a clever solution to solve the size problem. The converted weights are quite ok I think, but when you use the converted model in caffe, the size is still a problem.
