### ISSUE TITLE
how to user converted caffe model?

### ISSUE THREAD

**Issue by BowieHsu** [marvis/pytorch-caffe-darknet-convert#5]
Hi, marvis, thank you for your work again,  now I have trained a good model using pytorch on cifar100 datasets, when I try to convert this pytorch checkpoint into caffe model and deploy it,  the caffe predict result is different from pytorch's, after read the source code, I find there at least exists two differences:
1. caffe mean binaryproto is different from pytorch normalize parameter, I can not figure out calculate formula between them.
2. caffe reads img in BGR format which in pytorch should be RGB, if I train my pytorch checkpoint with BGR format img,  problem will be solved?
what should i do to solve those two problemes? can you give me some tips? Many thanks.

**Comment by marvis** [comment]
1. Please check the link below to see how to load caffe mean file in python
https://github.com/marvis/pytorch-caffe-darknet-convert/blob/master/caffenet.py#L92-L98
2. you can invoke cvtColor(img, img, CV_RGB2BGR);
