### ISSUE TITLE
tiny-yolo conversion from darknet is working, but all other models are not

### ISSUE THREAD

**Issue by StevenPuttemans** [marvis/pytorch-caffe-darknet-convert#6]
First of all, thanks for the conversion tools! It might be the way for converting my darknet models into caffemodels and then importing them directly into OpenCV with the new DNN module.

However module conversion does not seem to work:

`python darknet2caffe.py ../darknet_EAVISE/cfg/tiny-yolo-voc.cfg ../darknet_EAVISE/weights/tiny-yolo-voc.weights yolo.prototxt yolo.caffemodel` --> This command works just fine.

`python darknet2caffe.py ../darknet_EAVISE/cfg/darknet19.cfg ../darknet_EAVISE/weights/darknet19.weights yolo.prototxt yolo.caffemodel` --> this works also

But from the moment I take the yolov2 architecture it fails. 
Example:

`python darknet2caffe.py ../darknet_EAVISE/cfg/yolo-voc.2.0.cfg ../darknet_EAVISE/weights/yolo-voc.2.0.weights yolo.prototxt yolo.caffemodel`

Gives error

```
unknow layer type reorg 
Traceback (most recent call last):
  File "darknet2caffe.py", line 350, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 10, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 251, in cfg2prototxt
    prev_layer_id = layer_id + int(block['layers'])
ValueError: invalid literal for int() with base 10: '-1,-3'
```

And thus same for all the models people are now finetuning themselves. How hard would it be to include the reorg layer into the conversion?

**Comment by marvis** [comment]
It is very easy to add the conversion of reorg layer. But you need to provide the corresponding layer name in caffe.

**Comment by StevenPuttemans** [comment]
Hmm it seems that dropping the reorg layer might just drop the accuracy with only 1-2% following Darknet discussions, so it might be just better to remove them and retrain my network without them.

**Comment by marvis** [comment]
Interesting！
