### ISSUE TITLE
File "caffe2darknet.py", line 68, in caffe2darknet block['stride'] = conv_layer['convolution_param']['stride'] KeyError: 'stride'

### ISSUE THREAD

**Issue by ShadowChenCSD** [marvis/pytorch-caffe-darknet-convert#67]

**Comment by ShadowChenCSD** [comment]
Not all the caffe convolution operater has 'stride',such as VGG-16, so this error has occurred.
Can we do this:
```
block['stride'] = conv_layer['convolution_param']['stride'] if \
            conv_layer['convolution_param'].has_key('stride') else 0
```

**Comment by manikantarav** [comment]
i Got the same error, while trying to convert VGG_coco_SSD_300x300_iter_400000.caffemodel to darknet model. How can we resolve it? Need help here.

![Screenshot from 2019-03-29 18-59-53](https://user-images.githubusercontent.com/41368243/55235979-e12c0600-5254-11e9-97a2-989db3a71aec.png)

**Comment by shchae7** [comment]
@manikantarav Did you change the input part of the deploy.prototxt?, it seems at the moment caffe2darknet.py can't convert prototxt files with "Input" layer.
