### ISSUE TITLE
for yolov2  header = np.fromfile(fp, count=5, dtype=np.int32)

### ISSUE THREAD

**Issue by adeagle** [marvis/pytorch-caffe-darknet-convert#7]

**Comment by marvis** [comment]
Do you mean the header of the newest darknet contains 5 int？

**Comment by adeagle** [comment]
int major;
    int minor;
    int revision;

    fread(&major, sizeof(int), 1, fp);
    fread(&minor, sizeof(int), 1, fp);

    fread(&revision, sizeof(int), 1, fp);

    if ((major*10 + minor) >= 2){
        fread(net->seen, sizeof(size_t), 1, fp);

    } else {
        int iseen = 0;
        fread(&iseen, sizeof(int), 1, fp);

        *net->seen = iseen;
    }


sizeof(size_t)==8

**Comment by adeagle** [comment]
I use darknet2caffe.py to convert  tiny-yolo model,the caffe output's precision  is a bit lower than darknet
how to deal with it, any suggestion?

**Comment by marvis** [comment]
The normalized and maxpool (stride=1, size=2) in darknet are different from caffe

normalize_cpu:
x[index] = (x[index] - mean[f])/(sqrt(variance[f] + .00001f));

**Comment by adeagle** [comment]
it's very kind of you,do me a lot favor

**Comment by marvis** [comment]
you are welcome!
