### ISSUE TITLE
accuracy problem about darknet2caffe.py

### ISSUE THREAD

**Issue by adeagle** [marvis/pytorch-caffe-darknet-convert#8]
[yolo2caffe.tar.gz](https://github.com/marvis/pytorch-caffe-darknet-convert/files/1254062/yolo2caffe.tar.gz)

void normalize_cpu(float *x, float *mean, float *variance, int batch, int filters, int spatial)
{
    int b, f, i;
    for(b = 0; b < batch; ++b){
        for(f = 0; f < filters; ++f){
            for(i = 0; i < spatial; ++i){
                int index = b*filters*spatial + f*spatial + i;
                x[index] = (x[index] - mean[f])/(sqrt(variance[f]) + 1e-5);
            }
        }
    }
}
darknet detector  test face.data tinny-yolo-face.cfg tinny-yolo-face.backup 1.jpg
[236] face: 0.910748
[238] face: 0.819936
[241] face: 0.728282
[243] face: 0.706010

python test_yolo_v2.py
231 0.774435505004
371 0.744088620368
271 0.663471586181
216 0.497933280317
281 0.270810039193
336 0.241233347961

my problem is :why the diff so big

**Comment by adeagle** [comment]
caffe and darknet both latest

**Comment by marvis** [comment]
Can you check the output before region layer between darknet and caffe?

**Comment by adeagle** [comment]
i have figure out the problem:
original image will be paded by letterbox_image function in darknet
